GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/some_id

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test Dummy",
  "number": "40-20-1020304"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "40-20-1020304"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test Dummy"
}

###
PUT http://localhost:3001/api/persons/64de83941260ec933b70d199
Content-Type: application/json

{
  "name": "Test Dummy",
  "number": "00-00-0000000"
}